chore: update RWA to make running locally easier
cypress-io/cypress-realworld-app pull request #1524
Opened 2024-03-08 23:42 UTC by AtofStryker

I noticed after running the RWA earlier this week that there were some typing, linting, and other issues that make the app somewhat difficult to run locally. This PR addresses the typing issues, dependency issues, and old scaffolded data.

I had to downgrade `passport` due to https://github.com/jaredhanson/passport/issues/904

2024-03-11 15:43 UTC, cacieprins requested changes

2024-03-11 15:43 UTC, cacieprins commented on cypress/support/commands.ts
> +  // eslint-disable-next-line cypress/unsafe-to-chain-command
I think this works fine if we just stop chaining click onto scrollIntoView here. If this linter error isn't necessary, we should probably have a larger discussion about it.

2024-03-11 15:56 UTC, AtofStryker commented on cypress/support/commands.ts
> +  // eslint-disable-next-line cypress/unsafe-to-chain-command
we could just refactor this to 
```
cy.getBySel("transaction-list-filter-amount-range-button")
    .scrollIntoView()
cy.getBySel("transaction-list-filter-amount-range-button").click({ force: true });
```
but it seems a bit ridiculous that we are scrolling to something then forcing the click?

2024-03-11 17:02 UTC, cacieprins approved these changes

2024-03-11 17:03 UTC, AtofStryker commented on cypress/support/commands.ts
> +  // eslint-disable-next-line cypress/unsafe-to-chain-command
addressed in 71c38c9

2024-03-11 17:21 UTC, merged

2024-03-19 05:34 UTC, MikeMcC399 commented
@AtofStryker 

- Unfortunately this PR breaks RWA on Windows (see issue #1529).