fix for 6.0: not.be.visible -> not.exist
cypress-io/cypress-realworld-app pull request #648
Opened 2020-11-20 15:41 UTC by Bkucera

- fully backwards compatible

2020-11-20 17:03 UTC, Bkucera commented
awesome. seems to be passing now

2020-11-20 17:18 UTC, kevinold approved these changes

2020-11-20 17:26 UTC, kevinold commented on cypress/tests/ui/transaction-view.spec.ts
> +  it.only("transactions navigation tabs are hidden on a transaction view page", function () {
@Bkucera Remove `.only`

2020-11-20 17:27 UTC, kevinold requested changes
remove `.only`

2020-11-23 04:51 UTC, jennifer-shehane approved these changes

2020-11-23 04:52 UTC, jennifer-shehane commented
Going to merge this in so we can have tests runs in anticipation for 6.0 release.

2020-11-23 04:52 UTC, merged