fix(deps): add @types/cypress
cypress-io/cypress-realworld-app pull request #764
Opened 2021-02-05 19:11 UTC by diminutivesloop

The Cypress typings are referenced in `cypress\tsconfig.json` but they're not installed as a dependency so editors like VSCode show errors when opening the test files.

2021-02-05 20:26 UTC, kevinold requested changes
Thanks for your contribution!  One minor edit and we will merge.

2021-02-05 20:26 UTC, kevinold commented on package.json
> +    "@types/cypress": "^1.1.3",
@diminutivesloop Thanks for your contribution! Would you pin this version to 1.1.3. (remove the ^)

2021-02-05 20:30 UTC, bahmutov commented
What’s types/cypress for?

Sent from my iPhone

> On Feb 5, 2021, at 15:27, Kevin Old <notifications@github.com> wrote:
> 
> ﻿
> @kevinold requested changes on this pull request.
> 
> Thanks for your contribution! One minor edit and we will merge.
> 
> In package.json:
> 
> >      "@types/cors": "2.8.9",
> +    "@types/cypress": "^1.1.3",
> @diminutivesloop Thanks for your contribution! Would you pin this version to 1.1.3. (remove the ^)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-05 20:35 UTC, kevinold commented
Actually, this package is deprecated -- see https://www.npmjs.com/package/@types/cypress and we maintain our own types in Cypress itself. See https://github.com/cypress-io/cypress/tree/develop/cli/types

2021-02-05 20:35 UTC, closed without merging

2021-02-08 13:15 UTC, diminutivesloop commented
@kevinold Yeah I actually noticed this when I set up Cypress in my own project. Any idea why the built-in types weren't being picked up by VSCode for this project?

2021-02-08 14:54 UTC, kevinold commented
@diminutivesloop I'm not sure.  @bahmutov might have ideas.

2021-02-08 15:01 UTC, bahmutov commented
@diminutivesloop having global types is always problematic, read https://glebbahmutov.com/blog/local-cypress/

I personally just use JavaScript with `/// <reference types="cypress" />`